name: Build,Push & Deploying into Minikube

on:
  push:
    branches: [ "main" ]
    paths:
      - 'wisecow.sh'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'wisecow.sh'

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build and Push the Docker image   # means comment
      run: | 
        docker build . --file Dockerfile --tag ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_IMAGE }}:${{ github.run_number }}
        docker push ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_IMAGE }}:${{ github.run_number }}
  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Deploying to Minikube
      shell: 'C:\Program Files\Git\bin\bash.exe'
      run: |
        export DOCKER_REGISTRY=${{ vars.DOCKER_REGISTRY }}
        export DOCKER_IMAGE=${{ vars.DOCKER_IMAGE }}
        export BUILD_NUMBER=${{ github.run_number }}

        envsubst < k8s/deployment.yaml | kubectl apply -f -
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml